# create_invite_tokens.py
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app import create_app
from extensions import db
from models.invite_token import InviteToken

app = create_app()
app.app_context().push()  # push context so db operations work

# This will create only tables that do not exist
db.create_all()

print("Tables created successfully.")

"""
ALTER TABLE "user"
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- Replace "user_id_seq" with your actual sequence name
SELECT pg_get_serial_sequence('"user"', 'id');

-- Suppose it returns: user_id_seq
-- Then set it to the max existing id + 1:
SELECT setval('user_id_seq', (SELECT MAX(id) FROM "user"));
"""
