"""add_inventorykey_to_checkinitems

Revision ID: a41aef6abd42
Revises: 89f615af9aa1
Create Date: 2025-11-22 09:20:07.388989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a41aef6abd42'
down_revision: Union[str, None] = '89f615af9aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_tokens', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('invite_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_invite_tokens_token', table_name='invite_tokens')
    op.drop_constraint('invite_tokens_token_key', 'invite_tokens', type_='unique')
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=True)
    op.add_column('tblcheckinitems', sa.Column('inventorykey', sa.Integer(), nullable=True))
    op.drop_index('idx_inventory_custid', table_name='tblcustawngs')
    op.drop_index('idx_inventory_description_trgm', table_name='tblcustawngs', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_inventory_material_trgm', table_name='tblcustawngs', postgresql_ops={'material': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_customer_contact_trgm', table_name='tblcustomers', postgresql_ops={'contact': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_customer_name_trgm', table_name='tblcustomers', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_customer_source', table_name='tblcustomers')
    op.drop_index('idx_customer_state', table_name='tblcustomers')
    op.drop_index('idx_customers_contact_lower', table_name='tblcustomers')
    op.drop_index('idx_customers_custid_lower', table_name='tblcustomers')
    op.drop_index('idx_customers_name', table_name='tblcustomers')
    op.drop_index('idx_customers_name_lower', table_name='tblcustomers')
    op.alter_column('tblcustworkorderdetail', 'custid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tblcustworkorderdetail', 'datein',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tblcustworkorderdetail', 'rushorder',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'firmrush',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'source_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Denormalized customer source name for fast filtering/sorting. Synced from tblcustomers.source -> tblsource.ssource',
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'processingstatus',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_workorder_completed', table_name='tblcustworkorderdetail', postgresql_where='(datecompleted IS NOT NULL)')
    op.drop_index('idx_workorder_custid', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_datein', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_daterequired', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_no_int', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_pending', table_name='tblcustworkorderdetail', postgresql_where='(datecompleted IS NULL)')
    op.drop_index('idx_workorder_processing', table_name='tblcustworkorderdetail', postgresql_where='(processingstatus = true)')
    op.drop_index('idx_workorder_queue', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_rush', table_name='tblcustworkorderdetail', postgresql_where='(datecompleted IS NULL)')
    op.drop_index('idx_workorder_shipto', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_source_name', table_name='tblcustworkorderdetail')
    op.drop_index('idx_workorder_woname_trgm', table_name='tblcustworkorderdetail', postgresql_ops={'woname': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('tblorddetcustawngs', 'workorderno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tblorddetcustawngs', 'custid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_tblorddetcustawngs_workorderno', table_name='tblorddetcustawngs')
    op.drop_index('idx_workorderitem_custid', table_name='tblorddetcustawngs')
    op.drop_index('idx_workorderitem_workorderno', table_name='tblorddetcustawngs')
    op.create_index(op.f('ix_tblorddetcustawngs_workorderno'), 'tblorddetcustawngs', ['workorderno'], unique=False)
    op.alter_column('tblrepairorderfiles', 'repairorderno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tblrepairorderfiles', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_tblrepairorderfiles_repairorderno', table_name='tblrepairorderfiles')
    op.alter_column('tblrepairworkorderdetail', 'custid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tblrepairworkorderdetail', 'rushorder',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'firmrush',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'clean',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'cleanfirst',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'source_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Denormalized customer source name for fast filtering/sorting. Synced from tblcustomers.source -> tblsource.ssource',
               existing_nullable=True)
    op.drop_index('idx_repairorder_custid', table_name='tblrepairworkorderdetail')
    op.drop_index('idx_repairorder_datecompleted', table_name='tblrepairworkorderdetail')
    op.drop_index('idx_repairorder_item_type_trgm', table_name='tblrepairworkorderdetail', postgresql_ops={'ITEM TYPE': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_repairorder_location_trgm', table_name='tblrepairworkorderdetail', postgresql_ops={'location': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_repairorder_no_desc', table_name='tblrepairworkorderdetail')
    op.drop_index('idx_repairorder_pending', table_name='tblrepairworkorderdetail', postgresql_where='(datecompleted IS NULL)')
    op.drop_index('idx_repairorder_roname_trgm', table_name='tblrepairworkorderdetail', postgresql_ops={'roname': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_repairorder_source_name', table_name='tblrepairworkorderdetail')
    op.drop_index('idx_repairorder_type_of_repair_trgm', table_name='tblrepairworkorderdetail', postgresql_ops={'TYPE OF REPAIR': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('tblreporddetcustawngs', 'repairorderno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tblreporddetcustawngs', 'custid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_repairorderitem_repairorderno', table_name='tblreporddetcustawngs')
    op.drop_index('idx_tblreporddetcustawngs_repairorderno', table_name='tblreporddetcustawngs')
    op.create_index(op.f('ix_tblreporddetcustawngs_repairorderno'), 'tblreporddetcustawngs', ['repairorderno'], unique=False)
    op.alter_column('tblsource', 'ssource',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tblsource', 'sourceaddress',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcestate',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcecity',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcezip',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcephone',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcefax',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourceemail',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_source_ssource_trgm', table_name='tblsource', postgresql_ops={'ssource': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('idx_source_state', table_name='tblsource')
    op.alter_column('tblworkorderfiles', 'workorderno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tblworkorderfiles', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_tblworkorderfiles_workorderno', table_name='tblworkorderfiles')
    op.alter_column('user', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_tblworkorderfiles_workorderno', 'tblworkorderfiles', ['workorderno'], unique=False)
    op.alter_column('tblworkorderfiles', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tblworkorderfiles', 'workorderno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_source_state', 'tblsource', ['sourcestate'], unique=False)
    op.create_index('idx_source_ssource_trgm', 'tblsource', ['ssource'], unique=False, postgresql_ops={'ssource': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('tblsource', 'sourceemail',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcefax',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcephone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcezip',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcecity',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourcestate',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'sourceaddress',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tblsource', 'ssource',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tblreporddetcustawngs_repairorderno'), table_name='tblreporddetcustawngs')
    op.create_index('idx_tblreporddetcustawngs_repairorderno', 'tblreporddetcustawngs', ['repairorderno'], unique=False)
    op.create_index('idx_repairorderitem_repairorderno', 'tblreporddetcustawngs', ['repairorderno'], unique=False)
    op.alter_column('tblreporddetcustawngs', 'custid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tblreporddetcustawngs', 'repairorderno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_repairorder_type_of_repair_trgm', 'tblrepairworkorderdetail', ['TYPE OF REPAIR'], unique=False, postgresql_ops={'TYPE OF REPAIR': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_repairorder_source_name', 'tblrepairworkorderdetail', ['source_name'], unique=False)
    op.create_index('idx_repairorder_roname_trgm', 'tblrepairworkorderdetail', ['roname'], unique=False, postgresql_ops={'roname': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_repairorder_pending', 'tblrepairworkorderdetail', ['datecompleted'], unique=False, postgresql_where='(datecompleted IS NULL)')
    op.create_index('idx_repairorder_no_desc', 'tblrepairworkorderdetail', [sa.text('repairorderno DESC')], unique=False)
    op.create_index('idx_repairorder_location_trgm', 'tblrepairworkorderdetail', ['location'], unique=False, postgresql_ops={'location': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_repairorder_item_type_trgm', 'tblrepairworkorderdetail', ['ITEM TYPE'], unique=False, postgresql_ops={'ITEM TYPE': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_repairorder_datecompleted', 'tblrepairworkorderdetail', ['datecompleted'], unique=False)
    op.create_index('idx_repairorder_custid', 'tblrepairworkorderdetail', ['custid'], unique=False)
    op.alter_column('tblrepairworkorderdetail', 'source_name',
               existing_type=sa.TEXT(),
               comment='Denormalized customer source name for fast filtering/sorting. Synced from tblcustomers.source -> tblsource.ssource',
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'cleanfirst',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'clean',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'firmrush',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'rushorder',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'custid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_tblrepairorderfiles_repairorderno', 'tblrepairorderfiles', ['repairorderno'], unique=False)
    op.alter_column('tblrepairorderfiles', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tblrepairorderfiles', 'repairorderno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_tblorddetcustawngs_workorderno'), table_name='tblorddetcustawngs')
    op.create_index('idx_workorderitem_workorderno', 'tblorddetcustawngs', ['workorderno'], unique=False)
    op.create_index('idx_workorderitem_custid', 'tblorddetcustawngs', ['custid'], unique=False)
    op.create_index('idx_tblorddetcustawngs_workorderno', 'tblorddetcustawngs', ['workorderno'], unique=False)
    op.alter_column('tblorddetcustawngs', 'custid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tblorddetcustawngs', 'workorderno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_workorder_woname_trgm', 'tblcustworkorderdetail', ['woname'], unique=False, postgresql_ops={'woname': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_workorder_source_name', 'tblcustworkorderdetail', ['source_name'], unique=False)
    op.create_index('idx_workorder_shipto', 'tblcustworkorderdetail', ['shipto'], unique=False)
    op.create_index('idx_workorder_rush', 'tblcustworkorderdetail', ['rushorder', 'firmrush', 'datecompleted'], unique=False, postgresql_where='(datecompleted IS NULL)')
    op.create_index('idx_workorder_queue', 'tblcustworkorderdetail', ['queueposition', 'daterequired', 'datein', 'workorderno'], unique=False)
    op.create_index('idx_workorder_processing', 'tblcustworkorderdetail', ['processingstatus', 'datein'], unique=False, postgresql_where='(processingstatus = true)')
    op.create_index('idx_workorder_pending', 'tblcustworkorderdetail', ['datecompleted'], unique=False, postgresql_where='(datecompleted IS NULL)')
    op.create_index('idx_workorder_no_int', 'tblcustworkorderdetail', [sa.text('(workorderno::integer)')], unique=False)
    op.create_index('idx_workorder_daterequired', 'tblcustworkorderdetail', ['daterequired'], unique=False)
    op.create_index('idx_workorder_datein', 'tblcustworkorderdetail', [sa.text('datein DESC NULLS LAST')], unique=False)
    op.create_index('idx_workorder_custid', 'tblcustworkorderdetail', ['custid'], unique=False)
    op.create_index('idx_workorder_completed', 'tblcustworkorderdetail', [sa.text('datecompleted DESC NULLS LAST')], unique=False, postgresql_where='(datecompleted IS NOT NULL)')
    op.alter_column('tblcustworkorderdetail', 'processingstatus',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'source_name',
               existing_type=sa.TEXT(),
               comment='Denormalized customer source name for fast filtering/sorting. Synced from tblcustomers.source -> tblsource.ssource',
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'firmrush',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'rushorder',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'datein',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tblcustworkorderdetail', 'custid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_customers_name_lower', 'tblcustomers', [sa.text('lower(name)')], unique=False)
    op.create_index('idx_customers_name', 'tblcustomers', ['name'], unique=False)
    op.create_index('idx_customers_custid_lower', 'tblcustomers', [sa.text('lower(custid)')], unique=False)
    op.create_index('idx_customers_contact_lower', 'tblcustomers', [sa.text('lower(contact)')], unique=False)
    op.create_index('idx_customer_state', 'tblcustomers', ['state'], unique=False)
    op.create_index('idx_customer_source', 'tblcustomers', ['source'], unique=False)
    op.create_index('idx_customer_name_trgm', 'tblcustomers', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_customer_contact_trgm', 'tblcustomers', ['contact'], unique=False, postgresql_ops={'contact': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_inventory_material_trgm', 'tblcustawngs', ['material'], unique=False, postgresql_ops={'material': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_inventory_description_trgm', 'tblcustawngs', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_inventory_custid', 'tblcustawngs', ['custid'], unique=False)
    op.drop_column('tblcheckinitems', 'inventorykey')
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.create_unique_constraint('invite_tokens_token_key', 'invite_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_invite_tokens_token', 'invite_tokens', ['token'], unique=False)
    op.alter_column('invite_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('invite_tokens', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
