"""Add role column to user

Revision ID: 68dc43cdac7b
Revises: 
Create Date: 2025-08-22 15:26:57.509747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dc43cdac7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblCustAwngs',
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Material', sa.Text(), nullable=True),
    sa.Column('Condition', sa.Text(), nullable=True),
    sa.Column('Color', sa.Text(), nullable=True),
    sa.Column('SizeWgt', sa.Text(), nullable=True),
    sa.Column('Price', sa.Text(), nullable=True),
    sa.Column('CustID', sa.Text(), nullable=True),
    sa.Column('Qty', sa.Text(), nullable=True),
    sa.Column('InventoryKey', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('InventoryKey')
    )
    op.create_table('tblSource',
    sa.Column('SSource', sa.Text(), nullable=False),
    sa.Column('SourceAddress', sa.Text(), nullable=True),
    sa.Column('SourceState', sa.Text(), nullable=True),
    sa.Column('SourceCity', sa.Text(), nullable=True),
    sa.Column('SourceZip', sa.Text(), nullable=True),
    sa.Column('SourcePhone', sa.Text(), nullable=True),
    sa.Column('SourceFax', sa.Text(), nullable=True),
    sa.Column('SourceEmail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SSource')
    )
    op.create_table('tblCustomers',
    sa.Column('CustID', sa.Text(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Contact', sa.Text(), nullable=True),
    sa.Column('Address', sa.Text(), nullable=True),
    sa.Column('Address2', sa.Text(), nullable=True),
    sa.Column('City', sa.Text(), nullable=True),
    sa.Column('State', sa.Text(), nullable=True),
    sa.Column('ZipCode', sa.Text(), nullable=True),
    sa.Column('HomePhone', sa.Text(), nullable=True),
    sa.Column('WorkPhone', sa.Text(), nullable=True),
    sa.Column('CellPhone', sa.Text(), nullable=True),
    sa.Column('EmailAddress', sa.Text(), nullable=True),
    sa.Column('MailAddress', sa.Text(), nullable=True),
    sa.Column('MailCity', sa.Text(), nullable=True),
    sa.Column('MailState', sa.Text(), nullable=True),
    sa.Column('MailZip', sa.Text(), nullable=True),
    sa.Column('SourceOld', sa.Text(), nullable=True),
    sa.Column('Source', sa.Text(), nullable=True),
    sa.Column('SourceAddress', sa.Text(), nullable=True),
    sa.Column('SourceState', sa.Text(), nullable=True),
    sa.Column('SourceCity', sa.Text(), nullable=True),
    sa.Column('SourceZip', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['Source'], ['tblSource.SSource'], ),
    sa.PrimaryKeyConstraint('CustID')
    )
    op.create_table('tblCustWorkOrderDetail',
    sa.Column('WorkOrderNo', sa.String(), nullable=False),
    sa.Column('CustID', sa.String(), nullable=False),
    sa.Column('WOName', sa.String(), nullable=True),
    sa.Column('Storage', sa.String(), nullable=True),
    sa.Column('StorageTime', sa.String(), nullable=True),
    sa.Column('Rack#', sa.String(), nullable=True),
    sa.Column('SpecialInstructions', sa.Text(), nullable=True),
    sa.Column('RepairsNeeded', sa.Text(), nullable=True),
    sa.Column('SeeRepair', sa.String(), nullable=True),
    sa.Column('ReturnStatus', sa.String(), nullable=True),
    sa.Column('DateCompleted', sa.String(), nullable=True),
    sa.Column('Quote', sa.String(), nullable=True),
    sa.Column('Clean', sa.String(), nullable=True),
    sa.Column('Treat', sa.String(), nullable=True),
    sa.Column('RushOrder', sa.String(), nullable=True),
    sa.Column('DateRequired', sa.String(), nullable=True),
    sa.Column('DateIn', sa.String(), nullable=True),
    sa.Column('ShipTo', sa.String(), nullable=True),
    sa.Column('FirmRush', sa.String(), nullable=True),
    sa.Column('CleanFirstWO', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CustID'], ['tblCustomers.CustID'], ),
    sa.ForeignKeyConstraint(['ShipTo'], ['tblSource.SSource'], ),
    sa.PrimaryKeyConstraint('WorkOrderNo')
    )
    op.create_table('tblRepairWorkOrderDetail',
    sa.Column('RepairOrderNo', sa.String(), nullable=False),
    sa.Column('CustID', sa.String(), nullable=False),
    sa.Column('ROName', sa.String(), nullable=True),
    sa.Column('SOURCE', sa.String(), nullable=True),
    sa.Column('WO DATE', sa.String(), nullable=True),
    sa.Column('DATE TO SUB', sa.String(), nullable=True),
    sa.Column('DateRequired', sa.String(), nullable=True),
    sa.Column('RushOrder', sa.String(), nullable=True),
    sa.Column('FirmRush', sa.String(), nullable=True),
    sa.Column('QUOTE', sa.String(), nullable=True),
    sa.Column('QUOTE  BY', sa.String(), nullable=True),
    sa.Column('APPROVED', sa.String(), nullable=True),
    sa.Column('RACK#', sa.String(), nullable=True),
    sa.Column('STORAGE', sa.String(), nullable=True),
    sa.Column('ITEM TYPE', sa.String(), nullable=True),
    sa.Column('TYPE OF REPAIR', sa.String(), nullable=True),
    sa.Column('SPECIALINSTRUCTIONS', sa.Text(), nullable=True),
    sa.Column('CLEAN', sa.String(), nullable=True),
    sa.Column('SEECLEAN', sa.String(), nullable=True),
    sa.Column('CLEANFIRST', sa.String(), nullable=True),
    sa.Column('REPAIRSDONEBY', sa.String(), nullable=True),
    sa.Column('DateCompleted', sa.String(), nullable=True),
    sa.Column('MaterialList', sa.Text(), nullable=True),
    sa.Column('CUSTOMERPRICE', sa.String(), nullable=True),
    sa.Column('RETURNSTATUS', sa.String(), nullable=True),
    sa.Column('RETURNDATE', sa.String(), nullable=True),
    sa.Column('LOCATION', sa.String(), nullable=True),
    sa.Column('DATEOUT', sa.String(), nullable=True),
    sa.Column('DateIn', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CustID'], ['tblCustomers.CustID'], ),
    sa.PrimaryKeyConstraint('RepairOrderNo')
    )
    op.create_table('tblOrdDetCustAwngs',
    sa.Column('WorkOrderNo', sa.String(), nullable=False),
    sa.Column('CustID', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Material', sa.String(), nullable=False),
    sa.Column('Qty', sa.String(), nullable=True),
    sa.Column('Condition', sa.String(), nullable=True),
    sa.Column('Color', sa.String(), nullable=True),
    sa.Column('SizeWgt', sa.String(), nullable=True),
    sa.Column('Price', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CustID'], ['tblCustomers.CustID'], ),
    sa.ForeignKeyConstraint(['WorkOrderNo'], ['tblCustWorkOrderDetail.WorkOrderNo'], ),
    sa.PrimaryKeyConstraint('WorkOrderNo', 'Description', 'Material')
    )
    op.create_table('tblRepOrdDetCustAwngs',
    sa.Column('RepairOrderNo', sa.String(), nullable=False),
    sa.Column('CustID', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Material', sa.String(), nullable=False),
    sa.Column('Qty', sa.String(), nullable=True),
    sa.Column('Condition', sa.String(), nullable=True),
    sa.Column('Color', sa.String(), nullable=True),
    sa.Column('SizeWgt', sa.String(), nullable=True),
    sa.Column('Price', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['CustID'], ['tblCustomers.CustID'], ),
    sa.ForeignKeyConstraint(['RepairOrderNo'], ['tblRepairWorkOrderDetail.RepairOrderNo'], ),
    sa.PrimaryKeyConstraint('RepairOrderNo', 'Description', 'Material')
    )
    op.drop_table('repair_order_items')
    op.drop_table('photos')
    op.drop_table('repair_orders')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('inventory_items')
    op.drop_table('progress_tracking')
    op.drop_table('materials')
    op.drop_table('customers')
    op.drop_table('work_orders')
    op.drop_table('conditions')
    op.drop_table('colors')
    op.drop_table('work_order_items')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('role')

    op.create_table('work_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('work_order_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('material', sa.VARCHAR(length=100), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('size_weight', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conditions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('work_order_no', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('wo_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('storage', sa.VARCHAR(length=100), nullable=True),
    sa.Column('storage_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rack_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('special_instructions', sa.TEXT(), nullable=True),
    sa.Column('repairs_needed', sa.TEXT(), nullable=True),
    sa.Column('see_repair', sa.BOOLEAN(), nullable=True),
    sa.Column('return_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('date_in', sa.DATE(), nullable=True),
    sa.Column('date_required', sa.DATE(), nullable=True),
    sa.Column('quote', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('clean', sa.BOOLEAN(), nullable=True),
    sa.Column('treat', sa.BOOLEAN(), nullable=True),
    sa.Column('rush_order', sa.BOOLEAN(), nullable=True),
    sa.Column('firm_rush', sa.BOOLEAN(), nullable=True),
    sa.Column('clean_first_wo', sa.BOOLEAN(), nullable=True),
    sa.Column('ship_to', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_no')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('home_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('work_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cell_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=150), nullable=True),
    sa.Column('mail_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mail_city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mail_state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('mail_zip', sa.VARCHAR(length=20), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('progress_tracking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('work_order_id', sa.INTEGER(), nullable=True),
    sa.Column('pgrs_work_order_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pgrs_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pgrs_date_in', sa.DATE(), nullable=True),
    sa.Column('pgrs_date_updated', sa.DATE(), nullable=True),
    sa.Column('pgrs_source', sa.VARCHAR(length=200), nullable=True),
    sa.Column('wo_quote', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('on_deck_clean', sa.BOOLEAN(), nullable=True),
    sa.Column('tub', sa.BOOLEAN(), nullable=True),
    sa.Column('clean', sa.BOOLEAN(), nullable=True),
    sa.Column('treat', sa.BOOLEAN(), nullable=True),
    sa.Column('wrap_clean', sa.BOOLEAN(), nullable=True),
    sa.Column('notes_clean', sa.TEXT(), nullable=True),
    sa.Column('pgrs_repair_order_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('repair_quote', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('on_deck_repair', sa.BOOLEAN(), nullable=True),
    sa.Column('in_process', sa.BOOLEAN(), nullable=True),
    sa.Column('wrap_repair', sa.BOOLEAN(), nullable=True),
    sa.Column('repair_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('material', sa.VARCHAR(length=100), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('size_weight', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('qty', sa.INTEGER(), nullable=True),
    sa.Column('inventory_key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('repair_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('repair_order_no', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('ro_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('source', sa.VARCHAR(length=200), nullable=True),
    sa.Column('wo_date', sa.DATE(), nullable=True),
    sa.Column('date_to_sub', sa.DATE(), nullable=True),
    sa.Column('date_required', sa.DATE(), nullable=True),
    sa.Column('date_in', sa.DATE(), nullable=True),
    sa.Column('date_completed', sa.DATE(), nullable=True),
    sa.Column('date_out', sa.DATE(), nullable=True),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('rush_order', sa.BOOLEAN(), nullable=True),
    sa.Column('firm_rush', sa.BOOLEAN(), nullable=True),
    sa.Column('quote', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('quote_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('rack_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('storage', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type_of_repair', sa.VARCHAR(length=200), nullable=True),
    sa.Column('special_instructions', sa.TEXT(), nullable=True),
    sa.Column('repairs_done_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('material_list', sa.TEXT(), nullable=True),
    sa.Column('customer_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('clean', sa.BOOLEAN(), nullable=True),
    sa.Column('see_clean', sa.BOOLEAN(), nullable=True),
    sa.Column('clean_first', sa.BOOLEAN(), nullable=True),
    sa.Column('return_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_order_no')
    )
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('photo_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('repair_order_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('material', sa.VARCHAR(length=100), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('size_weight', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['repair_order_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tblRepOrdDetCustAwngs')
    op.drop_table('tblOrdDetCustAwngs')
    op.drop_table('tblRepairWorkOrderDetail')
    op.drop_table('tblCustWorkOrderDetail')
    op.drop_table('tblCustomers')
    op.drop_table('tblSource')
    op.drop_table('tblCustAwngs')
    # ### end Alembic commands ###
