"""Add invite_tokens table

Revision ID: b1897b8d63ad
Revises: 68dc43cdac7b
Create Date: 2025-08-22 16:21:21.202069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1897b8d63ad'
down_revision = '68dc43cdac7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=True)
    op.drop_table('tbljobscompletebydatetoexcel')
    op.drop_table('tblprogress')
    op.drop_table('tblmaterial')
    op.drop_table('tblincompletetoexcel')
    op.drop_table('Paste Errors')
    op.drop_table('Name AutoCorrect Log')
    op.drop_table('tbljobstoexcel')
    op.drop_table('tblphotos')
    op.drop_table('tbldescriptions')
    op.drop_table('tblcolor')
    op.drop_table('tbljobscompletebydatetoexcel_exporterrors')
    op.drop_table('tblwosummary')
    op.drop_table('tblitemscompletebydatetoexcel')
    op.drop_table('Switchboard Items')
    op.drop_table('tblorddetcustawngss')
    op.drop_table('tblcondition')
    op.drop_table('tblitemscompletebydatetoexcel_exporterrors')
    op.add_column('tblcustawngs', sa.Column('Description', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('Material', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('Condition', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('Color', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('SizeWgt', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('Price', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('CustID', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('Qty', sa.Text(), nullable=True))
    op.add_column('tblcustawngs', sa.Column('InventoryKey', sa.Text(), nullable=False))
    op.drop_column('tblcustawngs', 'custid')
    op.drop_column('tblcustawngs', 'condition')
    op.drop_column('tblcustawngs', 'material')
    op.drop_column('tblcustawngs', 'sizewgt')
    op.drop_column('tblcustawngs', 'description')
    op.drop_column('tblcustawngs', 'price')
    op.drop_column('tblcustawngs', 'color')
    op.drop_column('tblcustawngs', 'inventorykey')
    op.drop_column('tblcustawngs', 'qty')
    op.alter_column('tblcustomers', 'custid',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'tblcustomers', 'tblsource', ['source'], ['ssource'])
    op.add_column('tblcustworkorderdetail', sa.Column('rack#', sa.String(), nullable=True))
    op.alter_column('tblcustworkorderdetail', 'workorderno',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tblcustworkorderdetail', 'custid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tblcustworkorderdetail', 'woname',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'storage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'storagetime',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'seerepair',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'returnstatus',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'datecompleted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'quote',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'clean',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'treat',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'rushorder',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'daterequired',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'datein',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'shipto',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'firmrush',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'cleanfirstwo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tblcustworkorderdetail', 'tblcustomers', ['custid'], ['custid'])
    op.create_foreign_key(None, 'tblcustworkorderdetail', 'tblsource', ['shipto'], ['ssource'])
    op.drop_column('tblcustworkorderdetail', 'Rack#')
    op.alter_column('tblorddetcustawngs', 'workorderno',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tblorddetcustawngs', 'custid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tblorddetcustawngs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tblorddetcustawngs', 'material',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tblorddetcustawngs', 'qty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'condition',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'sizewgt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'price',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tblorddetcustawngs', 'tblcustworkorderdetail', ['workorderno'], ['workorderno'])
    op.create_foreign_key(None, 'tblorddetcustawngs', 'tblcustomers', ['custid'], ['custid'])
    op.add_column('tblrepairworkorderdetail', sa.Column('RepairOrderNo', sa.String(), nullable=False))
    op.add_column('tblrepairworkorderdetail', sa.Column('CustID', sa.String(), nullable=False))
    op.add_column('tblrepairworkorderdetail', sa.Column('ROName', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('SOURCE', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('DateRequired', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('RushOrder', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('FirmRush', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('QUOTE', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('APPROVED', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('STORAGE', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('SPECIALINSTRUCTIONS', sa.Text(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('CLEAN', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('SEECLEAN', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('CLEANFIRST', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('REPAIRSDONEBY', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('DateCompleted', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('MaterialList', sa.Text(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('CUSTOMERPRICE', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('RETURNSTATUS', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('RETURNDATE', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('LOCATION', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('DATEOUT', sa.String(), nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('DateIn', sa.String(), nullable=True))
    op.alter_column('tblrepairworkorderdetail', 'WO DATE',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'DATE TO SUB',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'QUOTE  BY',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'RACK#',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'ITEM TYPE',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'TYPE OF REPAIR',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'tblrepairworkorderdetail', 'tblcustomers', ['CustID'], ['custid'])
    op.drop_column('tblrepairworkorderdetail', 'roname')
    op.drop_column('tblrepairworkorderdetail', 'specialinstructions')
    op.drop_column('tblrepairworkorderdetail', 'repairorderno')
    op.drop_column('tblrepairworkorderdetail', 'custid')
    op.drop_column('tblrepairworkorderdetail', 'daterequired')
    op.drop_column('tblrepairworkorderdetail', 'quote')
    op.drop_column('tblrepairworkorderdetail', 'approved')
    op.drop_column('tblrepairworkorderdetail', 'customerprice')
    op.drop_column('tblrepairworkorderdetail', 'firmrush')
    op.drop_column('tblrepairworkorderdetail', 'returnstatus')
    op.drop_column('tblrepairworkorderdetail', 'dateout')
    op.drop_column('tblrepairworkorderdetail', 'materiallist')
    op.drop_column('tblrepairworkorderdetail', 'datecompleted')
    op.drop_column('tblrepairworkorderdetail', 'datein')
    op.drop_column('tblrepairworkorderdetail', 'location')
    op.drop_column('tblrepairworkorderdetail', 'cleanfirst')
    op.drop_column('tblrepairworkorderdetail', 'source')
    op.drop_column('tblrepairworkorderdetail', 'storage')
    op.drop_column('tblrepairworkorderdetail', 'rushorder')
    op.drop_column('tblrepairworkorderdetail', 'seeclean')
    op.drop_column('tblrepairworkorderdetail', 'clean')
    op.drop_column('tblrepairworkorderdetail', 'repairsdoneby')
    op.drop_column('tblrepairworkorderdetail', 'returndate')
    op.add_column('tblreporddetcustawngs', sa.Column('RepairOrderNo', sa.String(), nullable=False))
    op.add_column('tblreporddetcustawngs', sa.Column('CustID', sa.String(), nullable=False))
    op.add_column('tblreporddetcustawngs', sa.Column('Description', sa.String(), nullable=False))
    op.add_column('tblreporddetcustawngs', sa.Column('Material', sa.String(), nullable=False))
    op.add_column('tblreporddetcustawngs', sa.Column('Qty', sa.String(), nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('Condition', sa.String(), nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('Color', sa.String(), nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('SizeWgt', sa.String(), nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('Price', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tblreporddetcustawngs', 'tblcustomers', ['CustID'], ['custid'])
    op.create_foreign_key(None, 'tblreporddetcustawngs', 'tblrepairworkorderdetail', ['RepairOrderNo'], ['RepairOrderNo'])
    op.drop_column('tblreporddetcustawngs', 'repairorderno')
    op.drop_column('tblreporddetcustawngs', 'custid')
    op.drop_column('tblreporddetcustawngs', 'condition')
    op.drop_column('tblreporddetcustawngs', 'material')
    op.drop_column('tblreporddetcustawngs', 'sizewgt')
    op.drop_column('tblreporddetcustawngs', 'description')
    op.drop_column('tblreporddetcustawngs', 'price')
    op.drop_column('tblreporddetcustawngs', 'color')
    op.drop_column('tblreporddetcustawngs', 'qty')
    op.alter_column('tblsource', 'ssource',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.drop_index(op.f('idx_16507_sqlite_autoindex_user_1'), table_name='user')
    op.drop_index(op.f('idx_16507_sqlite_autoindex_user_2'), table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('idx_16507_sqlite_autoindex_user_2'), 'user', ['email'], unique=True)
    op.create_index(op.f('idx_16507_sqlite_autoindex_user_1'), 'user', ['username'], unique=True)
    op.alter_column('user', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tblsource', 'ssource',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('tblreporddetcustawngs', sa.Column('qty', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('sizewgt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblreporddetcustawngs', sa.Column('repairorderno', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tblreporddetcustawngs', type_='foreignkey')
    op.drop_constraint(None, 'tblreporddetcustawngs', type_='foreignkey')
    op.drop_column('tblreporddetcustawngs', 'Price')
    op.drop_column('tblreporddetcustawngs', 'SizeWgt')
    op.drop_column('tblreporddetcustawngs', 'Color')
    op.drop_column('tblreporddetcustawngs', 'Condition')
    op.drop_column('tblreporddetcustawngs', 'Qty')
    op.drop_column('tblreporddetcustawngs', 'Material')
    op.drop_column('tblreporddetcustawngs', 'Description')
    op.drop_column('tblreporddetcustawngs', 'CustID')
    op.drop_column('tblreporddetcustawngs', 'RepairOrderNo')
    op.add_column('tblrepairworkorderdetail', sa.Column('returndate', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('repairsdoneby', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('clean', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('seeclean', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('rushorder', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('storage', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('cleanfirst', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('datein', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('datecompleted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('materiallist', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('dateout', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('returnstatus', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('firmrush', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('customerprice', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('approved', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('daterequired', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('repairorderno', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('specialinstructions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblrepairworkorderdetail', sa.Column('roname', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tblrepairworkorderdetail', type_='foreignkey')
    op.alter_column('tblrepairworkorderdetail', 'updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'TYPE OF REPAIR',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'ITEM TYPE',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'RACK#',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'QUOTE  BY',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'DATE TO SUB',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblrepairworkorderdetail', 'WO DATE',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tblrepairworkorderdetail', 'DateIn')
    op.drop_column('tblrepairworkorderdetail', 'DATEOUT')
    op.drop_column('tblrepairworkorderdetail', 'LOCATION')
    op.drop_column('tblrepairworkorderdetail', 'RETURNDATE')
    op.drop_column('tblrepairworkorderdetail', 'RETURNSTATUS')
    op.drop_column('tblrepairworkorderdetail', 'CUSTOMERPRICE')
    op.drop_column('tblrepairworkorderdetail', 'MaterialList')
    op.drop_column('tblrepairworkorderdetail', 'DateCompleted')
    op.drop_column('tblrepairworkorderdetail', 'REPAIRSDONEBY')
    op.drop_column('tblrepairworkorderdetail', 'CLEANFIRST')
    op.drop_column('tblrepairworkorderdetail', 'SEECLEAN')
    op.drop_column('tblrepairworkorderdetail', 'CLEAN')
    op.drop_column('tblrepairworkorderdetail', 'SPECIALINSTRUCTIONS')
    op.drop_column('tblrepairworkorderdetail', 'STORAGE')
    op.drop_column('tblrepairworkorderdetail', 'APPROVED')
    op.drop_column('tblrepairworkorderdetail', 'QUOTE')
    op.drop_column('tblrepairworkorderdetail', 'FirmRush')
    op.drop_column('tblrepairworkorderdetail', 'RushOrder')
    op.drop_column('tblrepairworkorderdetail', 'DateRequired')
    op.drop_column('tblrepairworkorderdetail', 'SOURCE')
    op.drop_column('tblrepairworkorderdetail', 'ROName')
    op.drop_column('tblrepairworkorderdetail', 'CustID')
    op.drop_column('tblrepairworkorderdetail', 'RepairOrderNo')
    op.drop_constraint(None, 'tblorddetcustawngs', type_='foreignkey')
    op.drop_constraint(None, 'tblorddetcustawngs', type_='foreignkey')
    op.alter_column('tblorddetcustawngs', 'price',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'sizewgt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'condition',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'qty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblorddetcustawngs', 'material',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tblorddetcustawngs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tblorddetcustawngs', 'custid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tblorddetcustawngs', 'workorderno',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('tblcustworkorderdetail', sa.Column('Rack#', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tblcustworkorderdetail', type_='foreignkey')
    op.drop_constraint(None, 'tblcustworkorderdetail', type_='foreignkey')
    op.alter_column('tblcustworkorderdetail', 'updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'cleanfirstwo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'firmrush',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'shipto',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'datein',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'daterequired',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'rushorder',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'treat',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'clean',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'quote',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'datecompleted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'returnstatus',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'seerepair',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'storagetime',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'storage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'woname',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tblcustworkorderdetail', 'custid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tblcustworkorderdetail', 'workorderno',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('tblcustworkorderdetail', 'rack#')
    op.drop_constraint(None, 'tblcustomers', type_='foreignkey')
    op.alter_column('tblcustomers', 'custid',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('tblcustawngs', sa.Column('qty', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('inventorykey', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('sizewgt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tblcustawngs', sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tblcustawngs', 'InventoryKey')
    op.drop_column('tblcustawngs', 'Qty')
    op.drop_column('tblcustawngs', 'CustID')
    op.drop_column('tblcustawngs', 'Price')
    op.drop_column('tblcustawngs', 'SizeWgt')
    op.drop_column('tblcustawngs', 'Color')
    op.drop_column('tblcustawngs', 'Condition')
    op.drop_column('tblcustawngs', 'Material')
    op.drop_column('tblcustawngs', 'Description')
    op.create_table('tblitemscompletebydatetoexcel_exporterrors',
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('row', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblcondition',
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblorddetcustawngss',
    sa.Column('workorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sizewgt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('Switchboard Items',
    sa.Column('switchboardid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemnumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemtext', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('command', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('argument', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblitemscompletebydatetoexcel',
    sa.Column('clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datein', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sizewgt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datecompleted', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblwosummary',
    sa.Column('orderdetailid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workorderno', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tbljobscompletebydatetoexcel_exporterrors',
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('field', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('row', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblcolor',
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tbldescriptions',
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblphotos',
    sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photodate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tbljobstoexcel',
    sa.Column('clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datein', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sizewgt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datecompleted', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('Name AutoCorrect Log',
    sa.Column('Object Type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Object Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Control Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Property Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Old Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('New Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('Paste Errors',
    sa.Column('field0', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblincompletetoexcel',
    sa.Column('clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datein', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sourceold', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storagetime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Rack#', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialinstructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repairsneeded', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seerepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('returnstatus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rushorder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daterequired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipto', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblmaterial',
    sa.Column('material', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tblprogress',
    sa.Column('custid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgrsworkorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgrsname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgrsdatein', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgrsdateuptd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgrssource', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wo_quote', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ondeckclean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tub', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wrapclean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notesclean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pgrsrepairorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repair_quote', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ondeckrepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inprocess', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wraprepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repair_notes', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tbljobscompletebydatetoexcel',
    sa.Column('clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datein', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workorderno', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sourceold', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storagetime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Rack#', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialinstructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repairsneeded', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seerepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('returnstatus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rushorder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daterequired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipto', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    # ### end Alembic commands ###
